[package]
name = "arto-markdown"
description = "Arto's Markdown to HTML rendering pipeline"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
html-escape.workspace = true
lol_html.workspace = true
pulldown-cmark.workspace = true
serde.workspace = true
serde_yaml_ng = "0.10"
tracing.workspace = true
url = "2"

[dev-dependencies]
indoc.workspace = true
insta.workspace = true
serde_json.workspace = true
tempfile.workspace = true
