[package]
name = "arto-markdown"
version = "0.0.0"
authors = ["Alisue <lambdalisue@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
base64 = "0.22"
html-escape = "0.2"
lol_html = "3"
pulldown-cmark = "0.13"
serde_yaml = "0.9"
tracing = "0.1"
url = "2"

[dev-dependencies]
indoc = "2"
tempfile = "3"
