[package]
name = "arto"
description = "Arto, the Art of Reading Markdown"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
arboard = "3.6.1"
arto-config = { path = "../arto-config" }
arto-ipc = { path = "../arto-ipc" }
arto-keybindings = { path = "../arto-keybindings" }
arto-markdown = { path = "../arto-markdown" }
arto-page = { path = "../arto-page" }
base64.workspace = true
dark-light = "3.0.0"
chrono = { version = "0.4", features = ["serde"] }
clap.workspace = true
compile-time = "0.3"
dirs.workspace = true
dioxus = { version = "0.7.10", features = ["desktop"] }
dioxus-desktop = "0.7.10"
dioxus-sdk-window = "0.7.0"
dotenvy = "0.15.7"
html-escape.workspace = true
image = "0.25.10"
indoc.workspace = true
notify-debouncer-full = "0.7.0"
open = "5.4.3"
parking_lot = "0.12"
percent-encoding = "2.3"
rfd = { version = "0.17.2", default-features = false, features = ["xdg-portal"] }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio = { version = "1.52.3", features = ["time"] }
tracing.workspace = true
ureq = "3.4"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "fmt"] }
uuid = { version = "1.0", features = ["v4"] }
display-info = "0.5.9"
mouse_position = "0.1.4"

[target.'cfg(unix)'.dependencies]
signal-hook = "0.4"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.4"
objc2-app-kit = "0.3.2"
objc2-foundation = "0.3.2"
core-graphics = "0.25"
core-foundation = "0.10.1"
tracing-oslog = "0.3.0"

[dev-dependencies]
tempfile.workspace = true
